Shop by Category Widgets update
mayurk1320/nextjs-ignitiv-builderio-starter-storefront pull request #16
Opened 2024-01-04 12:22 UTC by Souvik-Ignitiv

Shop by Category Widgets dynamic category from builder io

2024-01-04 12:36 UTC, bsatignitiv requested changes

2024-01-04 12:36 UTC, bsatignitiv commented on cms/components/CmsShopByCategory/CmsShopByCategory.styles.ts
> +    background: '#e8ddfe',
Add color code to the theme file and use theme to provide color

2024-01-04 12:36 UTC, bsatignitiv commented on cms/components/CmsShopByCategory/CmsShopByCategory.tsx
> +                      // alt={item.imageAlt}
Remove comment

2024-01-09 07:25 UTC, Souvik-Ignitiv commented on cms/components/CmsShopByCategory/CmsShopByCategory.styles.ts
> +    background: '#e8ddfe',
resolves as per comment and color is coming from theme file

2024-01-09 07:25 UTC, Souvik-Ignitiv commented on cms/components/CmsShopByCategory/CmsShopByCategory.tsx
> +                      // alt={item.imageAlt}
resolves as per comment remove commented code

2024-01-09 10:15 UTC, merged