Feature Headless - Category Listing Page
mayurk1320/nextjs-ignitiv-builderio-starter-storefront pull request #17
Opened 2024-01-18 09:11 UTC by Souvik-Ignitiv

2024-01-18 12:13 UTC, bsatignitiv requested changes

2024-01-18 12:13 UTC, bsatignitiv commented on components/catrgory-list-page/Category/ChildCategory.styles.ts
> +    margin: '0 -16px',
Can we remove negative margin ?

2024-01-18 12:13 UTC, bsatignitiv commented on components/catrgory-list-page/Category/ChildCategory.styles.ts
> +      backgroundColor: '#ffffff',
1. Use color hex codes from theme file. If it's not available then add it in theme.
2. Make above change in whole file

2024-01-18 12:13 UTC, bsatignitiv commented on components/catrgory-list-page/Category/ChildCategory.styles.ts
> +    border: '1px solid ' + theme?.palette.primary.main,
Replace **'1px solid ' + theme?.palette.primary.main** with **`1px solid ${theme?.palette.primary.main}`**

2024-01-18 12:13 UTC, bsatignitiv commented on components/catrgory-list-page/Category/ChildCategory.tsx
> +interface Item {
Add 1 line space after import statements

2024-01-18 12:13 UTC, bsatignitiv commented on components/catrgory-list-page/Category/ChildCategory.tsx
> +  const handleItemClick = (item: Item) => {
Add 1 line space after useTranslation hook

2024-01-18 12:13 UTC, bsatignitiv commented on components/catrgory-list-page/Category/ChildCategory.tsx
> +  const isNextDisabled = currentIndex + itemsPerPage >= items.length
Move constants to the top

2024-01-18 12:13 UTC, bsatignitiv commented on components/catrgory-list-page/Category/ChildCategory.tsx
> +  }, [categories])
Move useEffect before functions

2024-01-18 12:13 UTC, bsatignitiv commented on components/catrgory-list-page/Category/ChildCategory.tsx
> +            {childCategory?.content?.name}
1. Create a getter function to get any data from childCategory object 
2. Make this change everywhere

2024-01-18 12:13 UTC, bsatignitiv commented on components/catrgory-list-page/HeroBanner/ClpHeroBanner.styles.ts
> +export const ClpHeroBannerStyle = {}
Remove this file if we have not added any styles

2024-01-18 12:13 UTC, bsatignitiv commented on components/catrgory-list-page/HeroBanner/ClpHeroBanner.tsx
> +const MainStyle = styled('div')({
What do you mean by MainStyle ? Give it a meaningful name.

2024-01-18 12:13 UTC, bsatignitiv commented on components/catrgory-list-page/HeroBanner/ClpHeroBanner.tsx
> +        <>
This fragment (<>) is not required. We can remove it.

2024-01-18 12:13 UTC, bsatignitiv commented on src/pages/clp/[categoryCode].tsx
> +  console.log('context', pageUrl, context.query.categoryCode)
Remove console

2024-01-19 04:48 UTC, Souvik-Ignitiv commented on components/catrgory-list-page/Category/ChildCategory.styles.ts
> +    margin: '0 -16px',
removed negative margin

2024-01-19 04:49 UTC, Souvik-Ignitiv commented on components/catrgory-list-page/Category/ChildCategory.styles.ts
> +      backgroundColor: '#ffffff',
change all the color and added them from them.ts

2024-01-19 04:49 UTC, Souvik-Ignitiv commented on components/catrgory-list-page/Category/ChildCategory.styles.ts
> +      backgroundColor: '#ffffff',
theme.ts

2024-01-19 04:49 UTC, Souvik-Ignitiv commented on components/catrgory-list-page/Category/ChildCategory.tsx
> +interface Item {
space added

2024-01-19 04:49 UTC, Souvik-Ignitiv commented on components/catrgory-list-page/Category/ChildCategory.tsx
> +  const handleItemClick = (item: Item) => {
space added

2024-01-19 04:50 UTC, Souvik-Ignitiv commented on components/catrgory-list-page/Category/ChildCategory.tsx
> +            {childCategory?.content?.name}
created getter function to get data

2024-01-19 04:50 UTC, Souvik-Ignitiv commented on components/catrgory-list-page/HeroBanner/ClpHeroBanner.tsx
> +const MainStyle = styled('div')({
change the name to HeroBanner Container

2024-01-19 04:51 UTC, Souvik-Ignitiv commented on src/pages/clp/[categoryCode].tsx
> +  console.log('context', pageUrl, context.query.categoryCode)
removed console

2024-01-19 04:51 UTC, Souvik-Ignitiv commented on components/catrgory-list-page/HeroBanner/ClpHeroBanner.styles.ts
> +export const ClpHeroBannerStyle = {}
removed the file

2024-01-19 04:52 UTC, Souvik-Ignitiv commented on components/catrgory-list-page/HeroBanner/ClpHeroBanner.tsx
> +        <>
remove line no 33 for 31 it was giving error

2024-01-19 05:03 UTC, merged